server:
  port: 8201
spring:
  application:
    name: springboot-sso-server8201
  redis:
    host: 123.56.25.98
    port: 6379
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    template-loader-path=classpath: /templates